# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832222fded6af6a1dba0cc073e43ee5fba0e68d63f84d9b0874d138ee3a9c159d930660de1c2624953d24f88644ced92b81478c21388cf4e5a7640d7b9c24c75

test:
  secret_key_base: c5609da07b9605822de1a0fbce0055b8db7bc3f8cf6ac21734668f95f2df6325c8d433f5991a621abbf4a4b2a0833788ffd87882919148b9c1dcf610567cc035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
